name:                algorithms-in-haskell
version:             0.1.0.0
github:              "tknawara/algorithms-in-haskell"
license:             BSD3
author:              "tknawara"
maintainer:          "tknawara"
copyright:           "2018 tknawara" 

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://gitlab.com/tarek-nawara/algorithms-in-haskell/blob/master/README.md>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- sort
- pqueue
- hspec

library:
  source-dirs: src

executables:
  algorithms-in-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algorithms-in-haskell

tests:
  algorithms-in-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algorithms-in-haskell
